In [1]:
import pandas as pd

In [2]:
nyc=pd.read_csv("ave_hi_nyc_jan_1895-2018.csv", header='infer')

In [3]:
nyc

Date  Value  Anomaly
0    189501   34.2     -3.2
1    189601   34.7     -2.7
2    189701   35.5     -1.9
3    189801   39.6      2.2
4    189901   36.4     -1.0
..      ...    ...      ...
119  201401   35.5     -1.9
120  201501   36.1     -1.3
121  201601   40.8      3.4
122  201701   42.8      5.4
123  201801   38.7      1.3

[124 rows x 3 columns]

In [4]:
nyc.columns

Index(['Date', 'Value', 'Anomaly'], dtype='object')

In [5]:
nyc.columns=['Date', 'Temperature', 'Aomaly']


In [6]:
nyc.head(6)

Date  Temperature  Aomaly
0  189501         34.2    -3.2
1  189601         34.7    -2.7
2  189701         35.5    -1.9
3  189801         39.6     2.2
4  189901         36.4    -1.0
5  190001         37.4     0.0

In [7]:
nyc.sample(5)

Date  Temperature  Aomaly
118  201301         40.8     3.4
99   199401         31.6    -5.8
36   193101         38.2     0.8
84   197901         38.6     1.2
97   199201         40.9     3.5

In [8]:
nyc.tail(6)

Date  Temperature  Aomaly
118  201301         40.8     3.4
119  201401         35.5    -1.9
120  201501         36.1    -1.3
121  201601         40.8     3.4
122  201701         42.8     5.4
123  201801         38.7     1.3

In [9]:
nyc.Date=nyc.Date.floordiv(100)

In [10]:
nyc.head()

Date  Temperature  Aomaly
0  1895         34.2    -3.2
1  1896         34.7    -2.7
2  1897         35.5    -1.9
3  1898         39.6     2.2
4  1899         36.4    -1.0

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
nyc['Date'].values

array([1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905,
       1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916,
       1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927,
       1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938,
       1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949,
       1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018], dtype=int64)

In [76]:
X_train, X_test, y_train, y_test = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, test_size=0.1, random_state=11)

In [77]:
X_train.shape

(93, 1)

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
linear_regression=LinearRegression()

In [80]:
linear_regression

LinearRegression()

In [81]:
linear_regression.fit(X=X_train, y=y_train)

LinearRegression()

In [82]:
linear_regression.coef_

array([0.01939167])

In [83]:
linear_regression.intercept_

-0.30779820252656975

In [84]:
0.01939167 *2024 - 0.30779820252656975

38.94094187747343

In [85]:
predicted = linear_regression.predict(X_test)

In [86]:
expected = y_test

In [87]:
predicted

array([37.85501484, 36.47820604, 37.93258153, 36.61394775, 36.74968946,
       38.68885679, 36.43942269, 37.13752293, 37.62231476, 37.5253564 ,
       37.00178122, 38.320415  , 37.19569795, 38.45615671, 36.55577273,
       37.25387297, 38.18467329, 37.89379819, 38.14588994, 38.63068177,
       38.04893157, 37.02117289, 37.11813126, 37.69988146, 36.73029779,
       37.64170644, 37.56413974, 38.10710659, 36.8660395 , 36.84664783,
       36.9436062 ])

In [88]:
expected

array([31.7, 35.5, 40.5, 29.8, 40.7, 34.8, 34.2, 38.2, 36.2, 42.5, 39.4,
       40.9, 39.8, 40.8, 37. , 45.7, 33. , 29.9, 38. , 42.4, 32.3, 33.8,
       38.5, 37.8, 36.1, 33.8, 42.4, 30.6, 38.4, 42.3, 39.7])

In [89]:
for p, e in zip(predicted[::], expected[::]):
    print(f'predicted: {p:.2f}, epected:{e:.2f}')

predicted: 37.86, epected:31.70
predicted: 36.48, epected:35.50
predicted: 37.93, epected:40.50
predicted: 36.61, epected:29.80
predicted: 36.75, epected:40.70
predicted: 38.69, epected:34.80
predicted: 36.44, epected:34.20
predicted: 37.14, epected:38.20
predicted: 37.62, epected:36.20
predicted: 37.53, epected:42.50
predicted: 37.00, epected:39.40
predicted: 38.32, epected:40.90
predicted: 37.20, epected:39.80
predicted: 38.46, epected:40.80
predicted: 36.56, epected:37.00
predicted: 37.25, epected:45.70
predicted: 38.18, epected:33.00
predicted: 37.89, epected:29.90
predicted: 38.15, epected:38.00
predicted: 38.63, epected:42.40
predicted: 38.05, epected:32.30
predicted: 37.02, epected:33.80
predicted: 37.12, epected:38.50
predicted: 37.70, epected:37.80
predicted: 36.73, epected:36.10
predicted: 37.64, epected:33.80
predicted: 37.56, epected:42.40
predicted: 38.11, epected:30.60
predicted: 36.87, epected:38.40
predicted: 36.85, epected:42.30
predicted: 36.94, epected:39.70


In [90]:
predict=(lambda date: linear_regression.coef_ * date + linear_regression.intercept_)

In [91]:
def computeTemp(date):
    return linear_regression.coef_ * date + linear_regression.intercept_    

In [92]:
computeTemp(2024)

array([38.94094855])

In [93]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [94]:
rmse = np.sqrt(mean_squared_error(expected, predicted))

In [95]:
print(f"Root Mean Square Error (RMSE): {rmse}")

Root Mean Square Error (RMSE): 4.160742885627116


In [75]:
#calculate root mean square error for each 
#50-50, 80-20, 90-10, 75-25