In [1]:
#Import libraries

In [2]:
from tensorflow.keras.datasets import mnist

In [3]:
#Load EMNIST dataset

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [5]:
# Flatten the images 

In [6]:
X_train = X_train.reshape((X_train.shape[0], -1)).astype('float32') / 255
X_test = X_test.reshape((X_test.shape[0], -1)).astype('float32') / 255

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
#Split data into training and test sets

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, random_state=0)

In [10]:
X_train.shape

(45000, 784)

In [11]:
X_test.shape

(15000, 784)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn=KNeighborsClassifier()

In [14]:
#Train classifier

In [15]:
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

In [16]:
#Make predictions

In [17]:
predicted = knn.predict(X=X_test)

In [18]:
expected = y_test

In [19]:
expected

array([3, 6, 6, ..., 9, 7, 2], dtype=uint8)

In [20]:
predicted

array([3, 6, 6, ..., 9, 7, 2], dtype=uint8)

In [21]:
#Accuracy

In [22]:
print(f'{knn.score(X_test, y_test):.2%}')

97.02%


In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion=confusion_matrix(y_true=expected, y_pred=predicted)

In [25]:
confusion

array([[1503,    0,    2,    0,    0,    2,    3,    0,    0,    0],
       [   0, 1720,    3,    0,    1,    0,    1,    2,    0,    1],
       [   9,   12, 1394,    6,    3,    1,    2,   23,    4,    4],
       [   0,    2,   11, 1498,    0,   14,    2,    8,    8,    5],
       [   1,    8,    1,    0, 1387,    0,    3,    4,    1,   29],
       [   6,    0,    2,   11,    4, 1298,   11,    1,    2,    7],
       [   4,    5,    2,    0,    3,   11, 1441,    1,    1,    0],
       [   2,   16,    4,    0,    3,    0,    0, 1493,    0,   17],
       [   8,   15,    9,    9,    8,   24,   10,    1, 1384,   16],
       [   2,    4,    1,   10,   15,    3,    2,   17,    4, 1435]],
      dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score, classification_report

In [28]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1510
           1       0.97      1.00      0.98      1728
           2       0.98      0.96      0.97      1458
           3       0.98      0.97      0.97      1548
           4       0.97      0.97      0.97      1434
           5       0.96      0.97      0.96      1342
           6       0.98      0.98      0.98      1468
           7       0.96      0.97      0.97      1535
           8       0.99      0.93      0.96      1484
           9       0.95      0.96      0.95      1493

    accuracy                           0.97     15000
   macro avg       0.97      0.97      0.97     15000
weighted avg       0.97      0.97      0.97     15000

